#ifndef _INC_BEST_TIME_TO_BUY_AND_SELL_STOCK_WITH_COOLDOWN_
#define _INC_BEST_TIME_TO_BUY_AND_SELL_STOCK_WITH_COOLDOWN_

#include "_common_all.h"
#include "_common_list.h"
#include "_common_binary_tree.h"

/* Generated by leetgen (github.com/sryanyuan/leetgen)
Say you have an array for which the ith element is the price of a given stock on day i.

Design an algorithm to find the maximum profit. You may complete as many transactions as you like (ie, buy one and sell one share of the stock multiple times) with the following restrictions:


	You may not engage in multiple transactions at the same time (ie, you must sell the stock before you buy again).
	After you sell your stock, you cannot buy stock on next day. (ie, cooldown 1 day)


Example:


Input: [1,2,3,0,2]
Output: 3 
Explanation: transactions = [buy, sell, cooldown, buy, sell]

*/

class BestTimeToBuyAndSellStockWithCooldown {
public:
	static void test() {
		
	}

	static int maxProfit(vector<int>& prices) {
        if (prices.size() <= 1) {
            return 0;
        }
		vector<int> profits(prices.size() - 1, 0);
        vector<int> dps(prices.size() - 1, 0);
        for (int i = 1; i < prices.size(); i++) {
            profits[i - 1] = prices[i] - prices[i - 1];
        }
        int res = 0;
        // Find first positive
        int fi = 0;
        for (fi; fi < profits.size(); ++fi) {
            if (profits[fi] > 0) {
                break;
            }
        }
        if (fi >= profits.size()) {
            return 0;
        }
        dps[fi] = profits[fi];
        for (int i = fi + 1; i < profits.size(); ++i) {
            
        }
	}
};

#endif
