#ifndef _INC_BINARY_TREE_ZIGZAG_LEVEL_ORDER_TRAVERSAL_
#define _INC_BINARY_TREE_ZIGZAG_LEVEL_ORDER_TRAVERSAL_

#include "_common_all.h"
#include "_common_list.h"
#include "_common_binary_tree.h"

/* Generated by leetgen (github.com/sryanyuan/leetgen)
Given a binary tree, return the zigzag level order traversal of its nodes' values. (ie, from left to right, then right to left for the next level and alternate between).


For example:
Given binary tree [3,9,20,null,null,15,7],

    3
   / \
  9  20
    /  \
   15   7



return its zigzag level order traversal as:

[
  [3],
  [20,9],
  [15,7]
]

*/

class BinaryTreeZigzagLevelOrderTraversal : public TreeNodeCls {
public:
	static void test() {
		
	}

	static vector<vector<int>> zigzagLevelOrder(TreeNode* root) {
        vector<vector<int>> res;
        if (nullptr == root) {
            return res;
        }
        vector<TreeNode*> nodes(1, root);
        int level = 0;
        while (!nodes.empty()) {
            vector<TreeNode*> cnodes;
            vector<int> vals;
            for (auto v : nodes) {
                vals.push_back(v->val);
                if (nullptr != v->left) {
                    cnodes.push_back(v->left);
                }
                if (nullptr != v->right) {
                    cnodes.push_back(v->right);
                }
            }
            if (level % 2 != 0) {
                std::reverse(vals.begin(), vals.end());
            }
            nodes = std::move(cnodes);
            res.push_back(std::move(vals));
            ++level;
        }
        return res;
	}
};

#endif
