#ifndef _INC_HOUSE_ROBBER_II_
#define _INC_HOUSE_ROBBER_II_

#include "_common_all.h"
#include "_common_list.h"
#include "_common_binary_tree.h"

/* Generated by leetgen (github.com/sryanyuan/leetgen)
You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed. All houses at this place are arranged in a circle. That means the first house is the neighbor of the last one. Meanwhile, adjacent houses have security system connected and it will automatically contact the police if two adjacent houses were broken into on the same night.

Given a list of non-negative integers representing the amount of money of each house, determine the maximum amount of money you can rob tonight without alerting the police.

Example 1:


Input: [2,3,2]
Output: 3
Explanation: You cannot rob house 1 (money = 2) and then rob house 3 (money = 2),
             because they are adjacent houses.


Example 2:


Input: [1,2,3,1]
Output: 4
Explanation: Rob house 1 (money = 1) and then rob house 3 (money = 3).
             Total amount you can rob = 1 + 3 = 4.
*/

class HouseRobberIi {
public:
	static void test() {
        int ar[] = {2,3,2};
        vector<int> nums(ar, ar + sizeof(ar) / sizeof(ar[0]));
		auto res = rob(nums);
	}

	static int rob(vector<int>& nums) {
        if (nums.size() == 1) {
            return nums[0];
        }
		auto fn = [&nums](bool head) -> int {
            int maxrob = 0;
            int prev2 = 0, prev = 0;
            int si = 0, ei = nums.size() - 1;
            if (head) {
                ++si;
            }
            if (!head) {
                --ei;
            }
            for (int i = si; i <= ei; i++) {
                int rc = std::max(prev2 + nums[i], prev);
                maxrob = std::max(maxrob, rc);
                prev2 = prev;
                prev = rc;
            }
            return maxrob;
        };
        return std::max(fn(true), fn(false));
	}
};

#endif
