#ifndef _INC_INSERTION_SORT_LIST_
#define _INC_INSERTION_SORT_LIST_

#include "_common_all.h"
#include "_common_list.h"
#include "_common_binary_tree.h"

/* Generated by leetgen (github.com/sryanyuan/leetgen)
Sort a linked list using insertion sort.





A graphical example of insertion sort. The partial sorted list (black) initially contains only the first element in the list.
With each iteration one element (red) is removed from the input data and inserted in-place into the sorted list
 




Algorithm of Insertion Sort:


	Insertion sort iterates, consuming one input element each repetition, and growing a sorted output list.
	At each iteration, insertion sort removes one element from the input data, finds the location it belongs within the sorted list, and inserts it there.
	It repeats until no input elements remain.



Example 1:


Input: 4->2->1->3
Output: 1->2->3->4


Example 2:


Input: -1->5->3->4->0
Output: -1->0->3->4->5

*/

class InsertionSortList : public SingleLinkedListCls {
public:
	static void test() {
		auto res = insertionSortList(stringToListNode("[4,2,1,3]"));
	}

	static ListNode* insertionSortList(ListNode* head) {
		if (nullptr == head) {
			return head;
		}
		ListNode *node = head->next;
        ListNode *tail = head;
        int maxStep = 1;
		while (node != nullptr) {
			ListNode *next = node->next;
            ListNode *prev = nullptr;
            ListNode *cur = head;
            int i = 0;
            for (i; i < maxStep; i++) {
                if (node->val < cur->val) {
                    tail->next = node->next;
                    node->next = cur;
                    if (nullptr == prev) {
                        head = node;
                    } else {
                        prev->next = node;
                    }
                    break;
                }
                prev = cur;
                cur = cur->next;
            }
            if (i >= maxStep) {
                tail = tail->next;
            }
            ++maxStep;
            node = next;
		}
        return head;
	}
};

#endif
