#ifndef _INC_MAXIMUM_PRODUCT_SUBARRAY_
#define _INC_MAXIMUM_PRODUCT_SUBARRAY_

#include "_common_all.h"
#include "_common_list.h"
#include "_common_binary_tree.h"

/* Generated by leetgen (github.com/sryanyuan/leetgen)
Given an integer array nums, find the contiguous subarray within an array (containing at least one number) which has the largest product.

Example 1:


Input: [2,3,-2,4]
Output: 6
Explanation: [2,3] has the largest product 6.


Example 2:


Input: [-2,0,-1]
Output: 0
Explanation: The result cannot be 2, because [-2,-1] is not a subarray.
*/

class MaximumProductSubarray {
public:
	static void test() {
		
	}

	static int maxProduct(vector<int>& nums) {
		
	}
};

#endif
