#ifndef _INC_PERFECT_SQUARES_
#define _INC_PERFECT_SQUARES_

#include "_common_all.h"
#include "_common_list.h"
#include "_common_binary_tree.h"

/* Generated by leetgen (github.com/sryanyuan/leetgen)
Given a positive integer n, find the least number of perfect square numbers (for example, 1, 4, 9, 16, ...) which sum to n.

Example 1:


Input: n = 12
Output: 3 
Explanation: 12 = 4 + 4 + 4.

Example 2:


Input: n = 13
Output: 2
Explanation: 13 = 4 + 9.
*/

class PerfectSquares {
public:
	static void test() {
		
	}

	static int numSquares(int n) {
		while (n % 4 == 0) {
            n /= 4;
        }
        if (n % 8 == 7) {
            return 4;
        }
        for (int l = 0; l * l <= n; l++) {
            int r = sqrt(n - l * l);
            if (l * l + r * r == n) {
                if (l == 0 || r == 0) {
                    return 1;
                }
                return 2;
            }
        }
        return 3;
	}
};

#endif
