#ifndef _INC_POPULATING_NEXT_RIGHT_POINTERS_IN_EACH_NODE_
#define _INC_POPULATING_NEXT_RIGHT_POINTERS_IN_EACH_NODE_

#include "_common_all.h"
#include "_common_list.h"
#include "_common_binary_tree.h"

/* Generated by leetgen (github.com/sryanyuan/leetgen)
Given a binary tree


struct TreeLinkNode {
  TreeLinkNode *left;
  TreeLinkNode *right;
  TreeLinkNode *next;
}


Populate each next pointer to point to its next right node. If there is no next right node, the next pointer should be set to NULL.

Initially, all next pointers are set to NULL.

Note:


	You may only use constant extra space.
	Recursive approach is fine, implicit stack space does not count as extra space for this problem.
	You may assume that it is a perfect binary tree (ie, all leaves are at the same level, and every parent has two children).


Example:

Given the following perfect binary tree,


     1
   /  \
  2    3
 / \  / \
4  5  6  7


After calling your function, the tree should look like:


     1 -> NULL
   /  \
  2 -> 3 -> NULL
 / \  / \
4->5->6->7 -> NULL

*/

class PopulatingNextRightPointersInEachNode : public TreeNodeCls {
private:
    struct TreeLinkNode {
        TreeLinkNode *left;
        TreeLinkNode *right;
        TreeLinkNode *next;
    };

public:
	static void test() {
		
	}

	static void connect(TreeLinkNode *root) {
		if (nullptr == root) {
            return;
        }
        if (nullptr != root->left) {
            root->left->next = root->right;
            // Right node must exists
            if (nullptr != root->next) {
                root->right->next = root->next->left;
            } else {
                root->right->next = nullptr;
            }
        }
        connect(root->left);
        connect(root->right);
	}
};

#endif
