#ifndef _INC_SORT_COLORS_
#define _INC_SORT_COLORS_

#include "_common_all.h"
#include "_common_list.h"
#include "_common_binary_tree.h"

/* Generated by leetgen (github.com/sryanyuan/leetgen)
Given an array with n objects colored red, white or blue, sort them in-place so that objects of the same color are adjacent, with the colors in the order red, white and blue.

Here, we will use the integers 0, 1, and 2 to represent the color red, white, and blue respectively.

Note: You are not suppose to use the library's sort function for this problem.

Example:


Input: [2,0,2,1,1,0]
Output: [0,0,1,1,2,2]

Follow up:


	A rather straight forward solution is a two-pass algorithm using counting sort.
	First, iterate the array counting number of 0's, 1's, and 2's, then overwrite array with total number of 0's, then 1's and followed by 2's.
	Could you come up with a one-pass algorithm using only constant space?

*/

class SortColors {
public:
	static void test() {
		
	}

	static void sortColors(vector<int>& nums) {
		int red = 0;
        int blue = nums.size() - 1;
        for (int i = 0; i <= blue; i++) {
            if (nums[i] == 0) {
                std::swap(nums[red], nums[i]);
                red++;
            } else if (nums[i] == 2) {
                std::swap(nums[blue], nums[i]);
                blue--;
                i--;
            }
        }
	}

    static void countSort(vector<int> &nums) {
        int cnts[3] = {0};
        for (auto v : nums) {
            cnts[v]++;
        }
        int index = 0;
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < cnts[i]; j++) {
                nums[index++] = i;
            }
        }
    }
};

#endif
