#ifndef _INC_SURROUNDED_REGIONS_
#define _INC_SURROUNDED_REGIONS_

#include "_common_all.h"
#include "_common_list.h"
#include "_common_binary_tree.h"

/* Generated by leetgen (github.com/sryanyuan/leetgen)
Given a 2D board containing 'X' and 'O' (the letter O), capture all regions surrounded by 'X'.

A region is captured by flipping all 'O's into 'X's in that surrounded region.

Example:


X X X X
X O O X
X X O X
X O X X


After running your function, the board should be:


X X X X
X X X X
X X X X
X O X X


Explanation:

Surrounded regions shouldn’t be on the border, which means that any 'O' on the border of the board are not flipped to 'X'. Any 'O' that is not on the border and it is not connected to an 'O' on the border will be flipped to 'X'. Two cells are connected if they are adjacent cells connected horizontally or vertically.
*/

class SurroundedRegions {
public:
	static void test() {
		vector<vector<char>> board;
        vector<char> row;
        row.push_back('O');
        row.push_back('O');
        board.push_back(std::move(row));
        row.push_back('O');
        row.push_back('O');
        board.push_back(std::move(row));
        solve(board);
	}

	static void solve(vector<vector<char>>& board) {
		for (int i = 0; i < board.size(); i++) {
            for (int j = 0; j < board[0].size(); j++) {
                if (i == 0 || i == board.size() - 1 || j == 0 || j == board[0].size() - 1) {
                    dfs(board, i, j);
                }
            }
        }
        for (int i = 0; i < board.size(); i++) {
            for (int j = 0; j < board[0].size(); j++) {
                if (board[i][j] == '#') {
                    board[i][j] = 'O';
                } else if (board[i][j] == 'O') {
                    board[i][j] = 'X';
                }
            }
        }
	}

    static void dfs(vector<vector<char>>& board, int i, int j) {
        static int offsets[] = {-1, 0, 1, 0, 0, -1, 0, 1};
        if (board[i][j] != 'O') {
            return;
        }
        board[i][j] = '#';
        for (int o = 0; o < sizeof(offsets) / sizeof(offsets[0]); o += 2) {
            int ni = i + offsets[o];
            int nj = j + offsets[o + 1];
            if (ni < 0 || ni >= board.size() || nj < 0 || nj >= board[0].size()) {
                continue;
            }
            dfs(board, ni, nj);
        }
    }
};

#endif
