#ifndef _INC_WORD_LADDER_
#define _INC_WORD_LADDER_

#include "_common_all.h"
#include "_common_list.h"
#include "_common_binary_tree.h"

/* Generated by leetgen (github.com/sryanyuan/leetgen)
Given two words (beginWord and endWord), and a dictionary's word list, find the length of shortest transformation sequence from beginWord to endWord, such that:


	Only one letter can be changed at a time.
	Each transformed word must exist in the word list. Note that beginWord is not a transformed word.


Note:


	Return 0 if there is no such transformation sequence.
	All words have the same length.
	All words contain only lowercase alphabetic characters.
	You may assume no duplicates in the word list.
	You may assume beginWord and endWord are non-empty and are not the same.


Example 1:


Input:
beginWord = "hit",
endWord = "cog",
wordList = ["hot","dot","dog","lot","log","cog"]

Output: 5

Explanation: As one shortest transformation is "hit" -> "hot" -> "dot" -> "dog" -> "cog",
return its length 5.


Example 2:


Input:
beginWord = "hit"
endWord = "cog"
wordList = ["hot","dot","dog","lot","log"]

Output: 0

Explanation: The endWord "cog" is not in wordList, therefore no possible transformation.




*/

class WordLadder {
public:
	static void test() {
		vector<string> ls;
        ls.push_back("hot");
        ls.push_back("dot");
        ls.push_back("dog");
        ls.push_back("lot");
        ls.push_back("log");
        ls.push_back("cog");
        auto res = ladderLength("hit", "cog", ls);
	}

	static int ladderLength(string beginWord, string endWord, vector<string>& wordList) {
		unordered_set<string> wpool(wordList.begin(), wordList.end());
        stack<string> words;
        stack<string> curws;
        words.push(beginWord);
        int cnt = 0;
        while (!words.empty()) {
            stack<string> nextWords;
            string w = std::move(words.top());
            words.pop();
            for (int i = 0; i < w.size(); i++) {
                for (int j = 'a'; j <= 'z'; j++) {
                    string nw = w;
                    nw[i] = j;
                    if (wpool.count(nw) != 0) {
                        if (nw == endWord) {
                            return cnt + 2;
                        }
                        wpool.erase(nw);
                        curws.push(std::move(nw));
                    }
                }
            }
            if (words.empty()) {
                words = std::move(curws);
                ++cnt;
            }
        }
        return 0;
	}
};

#endif
